# Change these first
owner: The-onefit
repo: uptime

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

assignees:
  - aminraeisi

sites:
  - name: Public
    url: $PUBLIC_URL
    icon: https://www.theonefitapp.com/assets/images/favicon_io/favicon-32x32.png
    maxResponseTime: 5000
  - name: Portal
    url: $PORTAL_URL
    icon: https://www.theonefitapp.com/assets/images/favicon_io/favicon-32x32.png
    maxResponseTime: 5000
  - name: Backend API
    url: $TRAINING_API_URL
    icon: https://www.theonefitapp.com/assets/images/favicon_io/favicon-32x32.png
    maxResponseTime: 5000

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  baseUrl: /uptime
  logoUrl: https://www.theonefitapp.com/assets/images/favicon_io/apple-touch-icon.png
  favicon: https://www.theonefitapp.com/assets/images/favicon_io/favicon-32x32.png
  name: ONEFIT Upptime
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
